name: publish
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set version
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile
        with:
          dir: src/doc/
          branch: main
          token: ${{ secrets.ACCESS_TOKEN }}